### ISSUE TITLE
torch_example.py not working

### ISSUE THREAD

**Issue by jakee417** [ryan112358/private-pgm#10]
I am trying to run [torch_example.py](https://github.com/ryan112358/private-pgm/blob/master/examples/torch_example.py) but I am getting the following error:
```
Traceback (most recent call last):
  File "/Users/jakeetaylor/private-pgm/examples/torch_example.py", line 68, in <module>
    model = engine.estimate(measurements, total=total, engine='RDA')
  File "/Users/jakeetaylor/private-pgm/.venv/lib/python3.10/site-packages/mbi/inference.py", line 77, in estimate
    self.dual_averaging(measurements, total, **options)
  File "/Users/jakeetaylor/private-pgm/.venv/lib/python3.10/site-packages/mbi/inference.py", line 180, in dual_averaging
    _, g = self._marginal_loss(u) # not interested in loss of this query point
  File "/Users/jakeetaylor/private-pgm/.venv/lib/python3.10/site-packages/mbi/inference.py", line 270, in _marginal_loss
    diff = c*(Q @ x - y)
TypeError: unsupported operand type(s) for -: 'numpy.ndarray' and 'Tensor'
```

**Comment by ryan112358** [comment]
Thanks for flagging.  My way of dealing with torch was super hacky and I didn't find much benefit to it.  I am investigating a JAX-based implementation which should allow me to get rid of this, so I'll leave this broken for now.

**Comment by ryan112358** [comment]
Decided to delete all torch code since it was adding code complexity and will be replaced shortly.
