### ISSUE TITLE
KeyError: 'age' when running mst.py

### ISSUE THREAD

**Issue by RexYuan** [ryan112358/private-pgm#17]
Using the default params of the adult dataset, I got
```
$ python mst.py 
Traceback (most recent call last):
  File "/Users/test/Library/Mobile Documents/com~apple~CloudDocs/Cloud/private-pgm/mechanisms/mst.py", line 199, in <module>
    synth = MST(data, args.epsilon, args.delta)
  File "/Users/test/Library/Mobile Documents/com~apple~CloudDocs/Cloud/private-pgm/mechanisms/mst.py", line 26, in MST
    cliques = select(data, rho / 3.0, log1)
  File "/Users/test/Library/Mobile Documents/com~apple~CloudDocs/Cloud/private-pgm/mechanisms/mst.py", line 96, in select
    candidates = [e for e in candidates if not ds.connected(*e)]
  File "/Users/test/Library/Mobile Documents/com~apple~CloudDocs/Cloud/private-pgm/mechanisms/mst.py", line 96, in <listcomp>
    candidates = [e for e in candidates if not ds.connected(*e)]
  File "/usr/local/anaconda3/envs/pgm/lib/python3.10/site-packages/scipy/_lib/_disjoint_set.py", line 195, in connected
    return self._indices[self[x]] == self._indices[self[y]]
  File "/usr/local/anaconda3/envs/pgm/lib/python3.10/site-packages/scipy/_lib/_disjoint_set.py", line 130, in __getitem__
    raise KeyError(x)
KeyError: 'age'
```

**Comment by ryan112358** [comment]
Thanks for flagging, I recently switched to a scipy-based implementation of DisjointSet  which introduced this regression.  Should be fixed now.
